// examples/vue-headless/src/components/ProcessedTable.vue
<template>
  <div>
    <div v-if="!pivotState">
      <p>Loading pivot state...</p>
    </div>
    <div v-else-if="!rowField || !colField || measures.length === 0">
      <p>Waiting for pivot configuration...</p>
      <div style="font-size: 12px; color: #666; margin-top: 8px;">
        Debug: rowField={{ !!rowField }}, colField={{ !!colField }}, measures={{ measures.length }}
      </div>
    </div>
    <div v-else-if="pageRows.length === 0">
      <p>No data found matching the current filters.</p>
      <div style="font-size: 12px; color: #666; margin-top: 8px;">
        Groups: {{ groups.length }}, UniqueRows: {{ uniqueRows.length }}, CurrentPage: {{ pagination.currentPage }}
      </div>
    </div>
    <table v-else style="width: 100%; border-collapse: collapse;">
      <thead>
        <tr>
          <th style="padding: 8px; background: #f4f7fa; border-bottom: 1px solid #e2e7ed; text-align: left;">
            {{ rowField?.caption }} / {{ colField?.caption }}
          </th>
          <th
            v-for="(col, i) in colOrder"
            :key="col"
            :colspan="measures.length"
            draggable="true"
            @dragstart="(e) => handleColDragStart(e, i)"
            @dragover.prevent
            @dragenter.prevent
            @drop="(e) => handleColDrop(e, i)"
            style="padding: 8px; background: #f4f7fa; border-bottom: 1px solid #e2e7ed; text-align: center; cursor: move;"
          >
            {{ col }}
          </th>
        </tr>
        <tr>
          <th 
            @click="() => $emit('toggleSort', rowField?.uniqueName)"
            style="padding: 8px; background: #f8f9fa; border-bottom: 1px solid #dee2e6; cursor: pointer; text-align: left;"
          >
            {{ rowField?.caption }}{{ rowSortClass }}
          </th>
          <template v-for="col in colOrder" :key="col">
            <th
              v-for="measure in measures"
              :key="`${col}-${measure.uniqueName}`"
              @click="() => $emit('toggleSort', measure.uniqueName, col, true)"
              style="padding: 8px; background: #f8f9fa; border-bottom: 1px solid #dee2e6; border-right: 1px solid #dee2e6; text-align: left; cursor: pointer;"
            >
              <div style="display: flex; align-items: center; justify-content: space-between;">
                <span>{{ measure.caption }}</span>
                <span v-if="currentStore.sort.field === measure.uniqueName" style="margin-left: 5px;">
                  {{ currentStore.sort.dir === 'asc' ? '▲' : '▼' }}
                </span>
              </div>
            </th>
          </template>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(rowVal, rIdx) in pageRows"
          :key="rowVal"
          draggable="true"
          @dragstart="(e) => handleRowDragStart(e, rIdx)"
          @dragover.prevent
          @dragenter.prevent
          @drop="(e) => handleRowDrop(e, rIdx, pageRows)"
          style="cursor: move;"
        >
          <td style="font-weight: bold; padding: 8px; border-bottom: 1px solid #dee2e6;">
            {{ rowVal }}
          </td>
          <template v-for="colVal in colOrder" :key="colVal">
            <td
              v-for="measure in measures"
              :key="`${rowVal}-${colVal}-${measure.uniqueName}`"
              @click="() => handleCellClick(rowVal, colVal, measure)"
              :title="getCellValue(rowVal, colVal, measure) > 0 ? 'Click to view underlying records' : ''"
              :style="{
                padding: '8px',
                borderBottom: '1px solid #eee',
                borderRight: '1px solid #f0f0f0',
                cursor: getCellValue(rowVal, colVal, measure) > 0 ? 'pointer' : 'default',
                textAlign: getTextAlignment(measure.uniqueName)
              }"
            >
              {{ formatCellValue(rowVal, colVal, measure) }}
            </td>
          </template>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
import { computed, defineOptions } from 'vue'

defineOptions({
  name: 'ProcessedTable'
})

// Types
interface AxisField { uniqueName: string; caption: string }
interface MeasureField { uniqueName: string; caption: string; aggregation: string }
interface UiStore { 
  colOrder: string[]
  rowOrder: string[]
  sort: { field: string | null; dir: 'asc' | 'desc' } 
}

interface Props {
  pivotState: any
  currentStore: UiStore
  pagination: { currentPage: number; pageSize: number }
  pivotRef: any
}

const props = defineProps<Props>()

// Emits
const emit = defineEmits<{
  toggleSort: [field: string, columnValue?: string, isMeasureHeader?: boolean]
  colDragStart: [index: number]
  colDrop: [index: number]
  rowDragStart: [index: number]
  rowDrop: [toIndex: number, visibleLabels: string[]]
  openDrillDown: [
    rowField: string,
    rowValue: string,
    colField: string,
    colValue: string,
    measureName: string,
    measureCaption: string,
    measureAgg: string,
    cellAgg: number
  ]
  updateStore: [updater: (store: UiStore) => UiStore]
}>()

// Computed properties
const rowField = computed(() => {
  let result = props.pivotState?.rows?.[0]
  
  // Fallback: if state doesn't have rows config, try to get it from the pivot ref
  if (!result && props.pivotRef) {
    const fullState = props.pivotRef?.getState?.()
    result = fullState?.rows?.[0]
  }
  
  console.log('ProcessedTable rowField:', result, 'from state:', !!props.pivotState)
  return result
})
const colField = computed(() => {
  let result = props.pivotState?.columns?.[0]
  
  // Fallback: if state doesn't have columns config, try to get it from the pivot ref
  if (!result && props.pivotRef) {
    const fullState = props.pivotRef?.getState?.()
    result = fullState?.columns?.[0]
  }
  
  console.log('ProcessedTable colField:', result)
  return result
})
const measures = computed(() => {
  let result = props.pivotState?.measures || []
  
  // Fallback: if state doesn't have measures config, try to get it from the pivot ref
  if ((!result || result.length === 0) && props.pivotRef) {
    const fullState = props.pivotRef?.getState?.()
    result = fullState?.measures || []
  }
  
  console.log('ProcessedTable measures:', result.length, result)
  return result
})

const groups = computed(() => {
  // First try to use the groups from the state (which should be filtered)
  let result = props.pivotState?.groups || []
  
  // If no groups in state, fallback to getGroupedData from pivot ref
  if (!result || result.length === 0) {
    result = (props.pivotRef?.getGroupedData?.() || []) as Array<{ 
      key?: string; 
      aggregates?: Record<string, number> 
    }>
  }
  
  console.log('ProcessedTable groups:', result.length, result)
  console.log('ProcessedTable using groups from:', props.pivotState?.groups ? 'state' : 'pivotRef')
  return result
})

const uniqueCols = computed(() => {
  const unique = Array.from(new Set(groups.value.map(g => {
    const key = g?.key ?? ''
    const parts = String(key).split('|')
    return (parts[1] || parts[0] || '') as string
  }))).filter(Boolean) as string[]
  return unique
})

const colOrder = computed(() => 
  (props.currentStore.colOrder.length ? props.currentStore.colOrder : uniqueCols.value)
    .filter(c => uniqueCols.value.includes(c))
)

const pageRows = computed(() => {
  const start = (props.pagination.currentPage - 1) * props.pagination.pageSize
  const end = start + props.pagination.pageSize
  const result = uniqueRows.value.slice(start, end)
  console.log('ProcessedTable pageRows:', result.length, 'from uniqueRows:', uniqueRows.value.length)
  return result
})

const uniqueRows = computed(() => {
  const allRowSet = new Set<string>()
  groups.value.forEach(g => {
    const parts = String(g?.key ?? '').split('|')
    if (parts[0]) allRowSet.add(parts[0])
  })
  
  let rows: string[] = Array.from(allRowSet)
  if (props.currentStore.rowOrder.length) {
    rows = props.currentStore.rowOrder.filter(v => rows.includes(v))
  }
  return rows
})

const rowSortClass = computed(() => 
  props.currentStore.sort.field === rowField.value?.uniqueName 
    ? ` sorted-${props.currentStore.sort.dir}` 
    : ''
)

// Methods
const toNum = (v: unknown): number => {
  const n = Number(v ?? 0)
  return Number.isFinite(n) ? n : 0
}

const getCellValue = (rowVal: string, colVal: string, measure: MeasureField): number => {
  const grp = groups.value.find((g) => {
    const key = g?.key ?? ''
    const parts = String(key).split('|')
    return parts[0] === rowVal && (parts[1] || parts[0]) === colVal
  })
  
  const aggKey = `${measure.aggregation}_${measure.uniqueName}`
  return toNum((grp?.aggregates || {})[aggKey])
}

const formatCellValue = (rowVal: string, colVal: string, measure: MeasureField): string => {
  const val = getCellValue(rowVal, colVal, measure)
  
  if (!Number.isFinite(val)) {
    return String(val ?? '0')
  }
  
  // Use the web component's formatValue method if available
  const formatted = props.pivotRef?.formatValue?.(val, measure.uniqueName)
  return formatted || val.toLocaleString()
}

const getTextAlignment = (fieldName: string): 'left' | 'right' | 'center' => {
  // Get text alignment from the web component
  return (props.pivotRef?.getFieldAlignment?.(fieldName) || 'right') as 'left' | 'right' | 'center'
}

const handleCellClick = (rowVal: string, colVal: string, measure: MeasureField) => {
  const val = getCellValue(rowVal, colVal, measure)
  const hasData = Number(val) > 0
  
  if (hasData && rowField.value && colField.value) {
    emit('openDrillDown',
      rowField.value.uniqueName,
      String(rowVal),
      colField.value.uniqueName,
      String(colVal),
      measure.uniqueName,
      measure.caption,
      measure.aggregation,
      val
    )
  }
}

// Drag and drop handlers
const handleColDragStart = (e: DragEvent, index: number) => {
  e.dataTransfer!.effectAllowed = 'move'
  e.dataTransfer!.setData('text/plain', String(index))
  emit('colDragStart', index)
}

const handleColDrop = (e: DragEvent, index: number) => {
  e.preventDefault()
  emit('colDrop', index)
}

const handleRowDragStart = (e: DragEvent, index: number) => {
  e.dataTransfer!.effectAllowed = 'move'
  e.dataTransfer!.setData('text/plain', String(index))
  emit('rowDragStart', index)
}

const handleRowDrop = (e: DragEvent, index: number, visibleLabels: string[]) => {
  e.preventDefault()
  emit('rowDrop', index, visibleLabels)
}
</script>

// examples/react-demo/src/minimalcomponent/ProcessedTable.tsx
import { PivotHeadEl } from '../components/PivotHead';

export interface SortState { field: string | null; dir: 'asc' | 'desc'; }
export interface UiModeStore { colOrder: string[]; rowOrder: string[]; sort: SortState }
export interface PivotState {
  rows?: Array<{ uniqueName: string; caption: string }>;
  columns?: Array<{ uniqueName: string; caption: string }>;
  measures?: Array<{ uniqueName: string; caption: string; aggregation: string }>;
  processedData?: { rows?: unknown[] } | null;
  rawData?: Array<Record<string, unknown>>;
  data?: Array<Record<string, unknown>>;
}

export interface PaginationState { currentPage: number; totalPages: number; pageSize: number }

export interface ProcessedTableProps {
  pivot: PivotHeadEl | null;
  pivotState: PivotState | null;
  store: UiModeStore;
  setStore: (updater: (prev: UiModeStore) => UiModeStore) => void;
  pagination: PaginationState;
  toggleSort: (field: string) => void;
  onColDragStart: (index: number) => void;
  onColDrop: (toIndex: number) => void;
  onRowDragStart: (index: number) => void;
  onRowDropProcessed: (toIndex: number, currentRows: string[]) => void;
  showDrillDownModal: (args: { title: string; summary: string; rows: Array<Record<string, unknown>> }) => void;
}

export default function ProcessedTable({ pivot, pivotState: st, store, pagination: pg, toggleSort, onColDragStart, onColDrop, onRowDragStart, onRowDropProcessed, showDrillDownModal }: ProcessedTableProps) {
  if (!st || !pivot) return (<table id="pivot-table"><thead /><tbody /></table>);

  const rowField = st.rows?.[0];
  const colField = st.columns?.[0];
  const measures = st.measures || [];
  if (!rowField || !colField || measures.length === 0) return (<table id="pivot-table"><thead /><tbody /></table>);

  const groups = (pivot.getGroupedData?.() || []) as Array<{ key?: string; aggregates?: Record<string, unknown> }>;
  const uniqueCols = Array.from(new Set(groups.map(g => (g.key ? (g.key.includes('|') ? g.key.split('|')[1] : g.key.split('|')[0]) : '')))).filter(Boolean) as string[];
  const colOrder = (store.colOrder.length ? store.colOrder : uniqueCols).filter(c => uniqueCols.includes(c));

  const processedRows = (st.processedData?.rows as unknown[]) || [];
  let uniqueRows: string[] = [];
  const seen = new Set<string>();
  processedRows.forEach(r => {
    const v = (Array.isArray(r) ? (r as unknown[])[0] : (r as Record<string, unknown>)[rowField.uniqueName]) as unknown;
    const sv = String(v ?? '');
    if (!seen.has(sv)) { seen.add(sv); uniqueRows.push(sv); }
  });
  if (store.rowOrder.length) uniqueRows = store.rowOrder.filter(v => uniqueRows.includes(v));

  const start = (pg.currentPage - 1) * pg.pageSize;
  const end = start + pg.pageSize;
  const pageRows = uniqueRows.slice(start, end);

  return (
    <table id="pivot-table" aria-label="Processed pivot table">
      <thead>
        <tr className="groups">
          <th className="draggable" data-drag="row-header">{rowField.caption} / {colField.caption}</th>
          {colOrder.map((c, i) => (
            <th
              key={`g-${c}-${i}`}
              className="draggable"
              draggable
              onDragStart={() => onColDragStart(i)}
              onDragOver={e => e.preventDefault()}
              onDrop={() => onColDrop(i)}
              data-type="col"
              data-index={i}
              colSpan={measures.length}
            >
              {c}
            </th>
          ))}
        </tr>
        <tr className="measures">
          <th
            className={`ph-sortable${store.sort.field === rowField.uniqueName ? ` ph-sorted-${store.sort.dir}` : ''}`}
            data-sort-field={rowField.uniqueName}
            onClick={() => toggleSort(rowField.uniqueName)}
            aria-sort={store.sort.field === rowField.uniqueName ? (store.sort.dir === 'asc' ? 'ascending' : 'descending') : 'none'}
            scope="col"
          >
            {rowField.caption}
          </th>
          {colOrder.flatMap((colVal) => (
            measures.map((m, mi) => (
              <th
                key={`m-${String(colVal)}-${m.uniqueName}-${m.aggregation}-${mi}`}
                className={`ph-sortable${store.sort.field === m.uniqueName ? ` ph-sorted-${store.sort.dir}` : ''}`}
                data-sort-field={m.uniqueName}
                onClick={() => toggleSort(m.uniqueName)}
                aria-sort={store.sort.field === m.uniqueName ? (store.sort.dir === 'asc' ? 'ascending' : 'descending') : 'none'}
                scope="col"
              >
                {m.caption}
              </th>
            ))
          ))}
        </tr>
      </thead>
      <tbody>
        {pageRows.map((rowVal, rIdx) => (
          <tr
            key={`r-${rowVal}-${rIdx}`}
            className="draggable"
            draggable
            onDragStart={() => onRowDragStart(rIdx)}
            onDragOver={e => e.preventDefault()}
            onDrop={() => onRowDropProcessed(rIdx, pageRows)}
            data-type="row"
            data-index={rIdx}
            data-value={rowVal}
          >
            <td><strong>{rowVal}</strong></td>
            {colOrder.flatMap(colVal => (
              measures.map(m => {
                const group = groups.find(g => {
                  const keys = g.key ? g.key.split('|') : [];
                  return keys[0] === rowVal && (keys[1] || keys[0]) === colVal;
                });
                const key = `${m.aggregation}_${m.uniqueName}`;
                const agg = group?.aggregates?.[key];
                const numAgg = typeof agg === 'number' ? agg : Number(agg) || 0;
                const display = typeof agg === 'number' ? agg.toLocaleString() : (agg ?? '0');
                const hasData = Number(numAgg) > 0;
                const openDetails = () => {
                  if (!hasData) return;
                  const stSnap = (st || {}) as { rawData?: Array<Record<string, unknown>>; data?: Array<Record<string, unknown>> };
                  const raw = stSnap.rawData || stSnap.data || [];
                  const subset = raw.filter(r => String(r[rowField.uniqueName] ?? '') === String(rowVal) && String(r[colField.uniqueName] ?? '') === String(colVal));
                  let computed = 0;
                  const nums = subset.map(r => Number((r as Record<string, unknown>)[m.uniqueName] ?? 0));
                  if (m.aggregation === 'avg') computed = nums.reduce((a, b) => a + b, 0) / (nums.length || 1);
                  else if (m.aggregation === 'max') computed = nums.length ? Math.max(...nums) : 0;
                  else if (m.aggregation === 'min') computed = nums.length ? Math.min(...nums) : 0;
                  else if (m.aggregation === 'count') computed = subset.length;
                  else computed = nums.reduce((a, b) => a + b, 0);
                  const aggDisplay = (Number.isFinite(numAgg) && numAgg !== 0 ? numAgg : computed).toLocaleString();
                  showDrillDownModal({
                    title: `${rowField.uniqueName}: ${rowVal}${colField.uniqueName ? `, ${colField.uniqueName}: ${colVal}` : ''}`,
                    summary: `Records: ${subset.length}. ${m.caption} (${m.aggregation}) = ${aggDisplay}`,
                    rows: subset,
                  });
                };
                return (
                  <td
                    key={`c-${rowVal}-${colVal}-${m.uniqueName}-${m.aggregation}`}
                    className={hasData ? 'drill-down-cell' : ''}
                    title={hasData ? 'Click to view underlying records' : ''}
                    onClick={openDetails}
                    onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openDetails(); } }}
                    role={hasData ? 'button' : undefined}
                    tabIndex={hasData ? 0 : undefined}
                    data-row-value={String(rowVal)}
                    data-column-value={String(colVal)}
                    data-measure-name={m.uniqueName}
                    data-measure-caption={m.caption}
                    data-measure-agg={m.aggregation}
                    data-row-field={rowField.uniqueName}
                    data-column-field={colField.uniqueName}
                    data-aggregate-value={numAgg}
                  >
                    {String(display)}
                  </td>
                );
              })
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
